type = "javascript"
account_id = "84360be8d748ddadfd6897136883929a"

[site]
bucket = "dist"
entry-point = "workers"

[env.dev]
name = "taiwanv-dev"
route = "taiwanv-dev.linnil1.me/*"
zone_id = "81f4ea11d5b83ab03a5b2c7cb73678eb"

[env.prod]
name = "taiwanv"
route = "taiwanv.linnil1.me/*"
zone_id = "81f4ea11d5b83ab03a5b2c7cb73678eb"
